import 'dart:ui';

import 'package:easy_localization/easy_localization.dart';

class MockAssetLoader extends AssetLoader {
  @override
  Future<Map<String, dynamic>> load(String path, Locale locale) async {
    return {
      "common": {
        "toggle_password_visibility": "Toggle password visibility",
        "cancel": "Cancel",
        "go_shopping": "Go Shopping",
        "retry": "Retry",
        "remove": "Remove",
        "add": "Add",
        "save": "Save",
        "delivery_instructions": "Delivery Instructions",
        "understood": "Understood",
        "add_to_cart_semantics": "Add {name} to cart",
        "back": "Back",
        "close": "Close",
        "see_more": "See more",
        "see_less": "See less",
        "next": "Next",
        "previous": "Previous",
        "submit": "Submit",
        "optional": "(Optional)",
        "required": "Required",
        "got_it": "Got it",
        "confirm": "Confirm",
        "download": "Download",
        "copy": "Copy",
        "close_button": "Close",
        "loading": "Loading...",
        "retry_later": "Please try again later",
        "delete": "Delete",
        "update": "Update",
        "clear": "Clear",
        "name": "Name",
        "email": "Email",
        "unknown": "Unknown",
      },
      "auth": {
        "welcome_back_subtitle": "Welcome back",
        "start_today": "Start today",
        "full_name": "Full Name",
        "full_name_hint": "Enter full name",
        "email_address": "Email Address",
        "email_hint": "Enter email",
        "password": "Password",
        "password_required": "Password required",
        "email_required": "Email required",
        "email_invalid": "Invalid email",
        "agree_to_prefix": "I agree to ",
        "terms_conditions": "Terms",
        "and_conjunction": " and ",
        "privacy_policy_link": "Privacy",
        "marketing_opt_in": "Marketing opt-in",
        "sign_in": "Sign In",
        "create_account": "Create Account",
        "forgot_password": "Forgot Password?",
        "or_continue_with": "Or continue with",
        "google_sign_in": "Sign in with Google",
        "sign_up_with_google": "Sign up with Google",
        "apple_sign_in": "Sign in with Apple",
        "sign_up_with_apple": "Sign up with Apple",
        "no_account": "No account? ",
        "already_have_account": "Already have an account? ",
        "sign_up": "Sign up",
        "sign_in_required": "Sign in required",
        "please_sign_in": "Please sign in",
        "need_account_access": "Please sign in to access your account",
        "feature_1": "Feature 1",
        "feature_2": "Feature 2",
        "feature_3": "Feature 3",
        "sign_out": "Sign Out",
        "validation": {
          "password_min_8": "Password must be at least 8 characters",
          "password_weak": "Weak password",
          "email_invalid_validation": "Please enter a valid email address",
        },
        "errors": {"registration_success": "Registration successful! Verification email sent to {email}."},
        "reset_password": "Reset Password",
        "reset_password_desc": "Enter email to reset",
        "reset_password_success": "Email sent",
        "back_to_login": "Back to Login",
        "account_deleted": "Account deleted",
        "reset_link_invalid": "Link invalid",
        "reset_password_title": "Reset",
        "create_new_password": "New Password",
        "go_to_login": "Go to Login",
      },
      "app": {"tagline": "Test Tagline"},
      "product": {
        "a11y_regular": "Regular product",
        "a11y_on_sale": "Sale product",
        "no_reviews_card": "No reviews",
        "ships_from_label": "Ships from {locations}",
        "ships_from_worldwide": "Ships from {count} locations",
        "trending_hot": "HOT",
        "trending_rising": "RISING",
        "out_of_stock_label": "OUT OF STOCK",
        "not_found": "Not found",
        "not_found_desc": "Product not found",
        "watch_video": "Watch video",
        "share": "Share",
        "share_text": "Check this {productName}",
        "go_back": "Go back",
        "price": "Price",
        "delivery_free": "Free delivery",
        "description": "Description",
        "seller_info": "Seller info",
        "trust_ships_ca": "Ships from Canada",
        "details": {"delivery_information": "Delivery Info", "international_disclaimer": "Intl disclaimer"},
        "ships_from": "Ships from",
        "tracking": "Tracking",
        "tracking_available": "Available",
        "tracking_limited": "Limited",
        "free_shipping": "Free shipping",
        "low_stock": "Low stock",
        "quantity": "Quantity",
        "buy_now": "Buy now",
        "add_to_cart": "Add to cart",
        "reviews_title": "Reviews",
        "no_reviews_yet": "No reviews yet",
        "reviews_load_error": "Error loading reviews",
        "ratings_no_text_one": "{count} rating",
        "ratings_no_text_other": "{count} ratings",
        "metric_response": "Response",
        "metric_ships_in": "Ships in",
        "metric_positive": "Positive",
        "image_semantics": "Image {n} of {total}",
        "verified_purchase": "Verified purchase",
        "seller_response": "Seller response",
        "helpful_question": "Helpful?",
        "helpful_yes_count": "Yes ({count})",
        "helpful_vote_thanks": "Thanks",
        "helpful_vote_error": "Error",
        "notify_me": "Notify me",
        "notify_cancel": "Cancel notification",
        "out_of_stock": "Out of stock",
        "own_product_title": "Your product",
        "own_product_msg": "You cannot buy your own product",
        "add_product": "Add Product",
        "new_product": "New Product",
        "product_details": "Product Details",
        "name_desc_pricing": "Name, Description & Pricing",
        "enter_product_name": "Enter name",
        "describe_product": "Describe it",
        "stock": "Stock",
        "compare_at_price_learn_more": "Learn more",
        "compare_at_price_info_body": "Info body",
        "min_order_qty": "Min order",
        "free_shipping_info_body": "Free shipping info",
        "tax_code_label": "Tax code",
        "tax_code_hint": "Hint",
        "tax_code_learn_more": "Learn more",
        "stripe_tax_codes": "Stripe tax codes",
        "stripe_tax_codes_body": "Stripe info",
        "sku_optional": "SKU (optional)",
        "sku_hint": "SKU hint",
        "sku_what_is": "What is SKU?",
        "sku": "SKU",
        "sku_info_body": "SKU info",
        "product_condition": "Condition",
        "condition_new": "New",
        "condition_like_new": "Like New",
        "condition_good": "Good",
        "condition_fair": "Fair",
        "condition_for_parts": "For parts",
        "french_section_title": "French translation",
        "french_section_subtitle": "Subtitle",
        "name_french": "Name (FR)",
        "name_french_hint": "Hint (FR)",
        "description_french": "Desc (FR)",
        "description_french_hint": "Hint (FR)",
        "variant_builder": "Variants",
        "variant_builder_desc": "Desc",
        "has_variants": "Has variants",
        "has_variants_desc": "Desc",
        "product_media": "Media",
        "photos_and_video": "Photos & Video",
        "delivery_shipping": "Delivery",
        "shipping_options": "Options",
        "digital_product_label": "Digital",
        "no_shipping_needed": "No shipping",
        "digital_info_title": "Digital Info",
        "digital_info_body": "Body",
        "perishable_item": "Perishable",
        "perishable_info_title": "Title",
        "perishable_info_body": "Body",
        "age_restricted_item": "Age restricted",
        "age_restricted_info_title": "Title",
        "age_restricted_info_body": "Body",
        "standard_delivery": "Standard",
        "standard_delivery_info_body": "Body",
        "days_label": "days",
        "est_business_days_hint": "Hint",
        "price_dollar": r"$",
        "free_hint": "Free",
        "express_delivery": "Express",
        "express_delivery_info_body": "Body",
        "same_day_delivery": "Same day",
        "same_day_delivery_info_body": "Body",
        "bulk_shipping_discounts": "Discounts",
        "encourage_larger_orders": "Encourage",
        "three_plus_items": "3+",
        "five_plus_items": "5+",
        "percent_off": "% off",
        "cost_extra_item": "Extra cost",
        "max_per_shipment": "Max per shipment",
        "unlimited_hint": "Unlimited",
        "multi_item_learn_more": "Learn more",
        "multi_item_shipping_title": "Title",
        "multi_item_shipping_body": "Body",
        "package_location": "Location",
        "dimensions_pickup": "Dimensions",
        "local_pickup_only": "Local pickup",
        "local_pickup_info_body": "Body",
        "weight": "Weight",
        "length_cm": "Length",
        "width_cm": "Width",
        "height_cm": "Height",
        "weight_dimensions_learn_more": "Learn more",
        "weight_dimensions_info_title": "Title",
        "weight_dimensions_info_body": "Body",
        "warehouse_no_locations_hint": "No locations",
        "warehouse_add_button": "Add location",
        "warehouse_manual_address": "Manual address",
        "street_address": "Street",
        "street_hint": "Hint",
        "apartment_unit": "Apartment",
        "apartment_hint": "Hint",
        "city": "City",
        "province": "Province",
        "postal_code": "Postal code",
        "supplier_inventory": "Supplier",
        "cost_margins_stock": "Cost",
        "supplier_info": "Supplier info",
        "supplier_platform": "Platform",
        "intl_label": "International",
        "supplier_cost_banner": "Banner",
        "supplier_cost": "Cost",
        "currency_label": "Currency",
        "supplier_sku": "Supplier SKU",
        "supplier_url": "URL",
        "ship_days": "Days",
        "has_tracking": "Tracking",
        "supplier_tracking_title": "Title",
        "supplier_tracking_body": "Body",
        "internal_notes": "Notes",
        "inventory_settings": "Inventory settings",
        "manage_inventory": "Manage",
        "manage_inventory_subtitle": "Subtitle",
        "inventory_management_title": "Title",
        "inventory_management_body": "Body",
        "track_quantity_subtitle": "Track",
        "track_quantity_info_body": "Body",
        "allow_backorders": "Backorders",
        "allow_backorders_subtitle": "Subtitle",
        "allow_backorders_info_body": "Body",
        "low_stock_alert": "Alert",
        "low_stock_alert_subtitle": "Subtitle",
        "photos_count": "{count} photos",
        "add_photo": "Add photo",
        "video_count": "{count} videos",
        "edit_product": "Edit Product",
        "basic_info": "Basic Info",
        "product_name": "Product Name",
        "product_name_hint": "Enter product name",
        "product_description": "Product Description",
        "product_description_hint": "Enter description",
        "pricing_inventory": "Pricing & Inventory",
        "price_cad": "Price (CAD)",
        "price_hint": "0.00",
        "compare_at_price": "Compare at Price",
        "compare_at_price_hint": "0.00",
        "stock_quantity": "Stock Quantity",
        "stock_hint": "0",
        "category": "Category",
        "select_category": "Select Category",
        "images_video": "Images & Video",
        "add_images": "Add Images",
        "add_video": "Add Video",
        "shipping_delivery": "Shipping & Delivery",
        "is_digital": "Digital Product",
        "is_perishable": "Perishable",
        "weight_kg": "Weight (kg)",
        "dimensions_cm": "Dimensions (cm)",
        "save_draft": "Save Draft",
        "publish_product": "Publish",
        "updating": "Updating...",
        "publishing": "Publishing...",
        "success_added": "Product added",
        "success_updated": "Product updated",
        "basic_information": "Basic Information",
        "please_enter_name": "Enter name",
        "please_enter_description": "Enter description",
        "please_enter_price": "Enter price",
        "sold_out": "Sold out",
        "enter_quantity": "Enter quantity",
        "invalid_price": "Invalid price",
        "compare_at_price_must_be_higher": "Must be higher",
        "invalid_tax_code": "Invalid tax code",
        "mark_sold_out": "Mark sold out",
        "digital_subtitle": "Subtitle",
        "restrict_50km": "Restrict 50km",
        "perishable_subtitle": "Perishable subtitle",
        "product_location": "Location",
        "images": "Images",
        "remove_image": "Remove image",
        "save_changes": "Save Changes",
        "updated_success": "Success",
        "approval_rejected_title": "Rejected",
        "approval_rejected_generic": "Generic rejection",
        "under_review_title": "Under review",
        "under_review_edit_note": "Review note",
        "digital_type_software": "Software",
        "digital_type_book": "Book",
        "download_links": "Downloads",
        "mac_os_label": "macOS",
        "windows_label": "Windows",
        "linux_label": "Linux",
        "device_limit_label": "Device limit",
        "device_limit_hint": "Hint",
        "reenter_download_url_update": "Re-enter URL",
        "book_download_url": "Book URL",
        "invalid_postal": "Invalid postal code",
        "product_video": "Product Video",
        "digital_product": "Digital Product",
        "local_delivery_only": "Local delivery only",
      },
      "home": {
        "tagline": "Marketplace",
        "search_products": "Search products",
        "privacy_policy": "Privacy Policy",
        "terms_of_service": "Terms of Service",
        "copyright": "© 2024",
        "sort_by": "Sort by",
        "filter_price": "Price Filter",
        "canada_only": "Canada Only",
        "error_loading_products": "Error loading products",
        "settings": "Settings",
        "shopping_cart": "Cart",
        "category_all": "All",
        "no_products_found": "No products found",
        "try_adjusting": "Try adjusting filters",
      },
      "cart": {
        "your_cart": "Your Cart",
        "sign_in_subtitle": "Sign in to see your cart",
        "loading_cart": "Loading cart...",
        "unable_to_load": "Unable to load",
        "load_error_subtitle": "Load error",
        "empty_cart": "Empty cart",
        "empty_cart_desc": "Your cart is empty",
        "unavailable_items_warning": "{count} items unavailable",
        "item_load_error": "Item load error",
        "item_no_longer_available": "Item no longer available",
        "subtotal_with_count": "Subtotal ({count} items)",
        "service_fees": "Service Fees",
        "service_fee_tooltip": "Fee: {percent}%",
        "service_fee_info": "Info: {percent}%",
        "tax_estimate": "Tax Estimate",
        "tax_tooltip": "Tax Tooltip",
        "tax_estimate_title": "Tax Estimate Title",
        "tax_info": "Tax Info",
        "add_instructions_optional": "Add instructions (optional)",
        "delivery_instructions_desc": "Instructions for delivery",
        "delivery_hint": "Delivery hint",
        "proceed_to_checkout": "Proceed to Checkout",
        "free_shipping_qualified": "Free shipping qualified",
        "free_shipping_progress": "${"{"}amount} more for free shipping",
        "free_shipping_threshold": "Threshold reached",
        "item_note_label": "Note",
        "view_cart": "View Cart",
      },
      "checkout": {
        "checkout": "Checkout",
        "estimated_total": "Estimated Total",
        "step_cart": "Cart",
        "step_details": "Details",
        "step_confirm": "Confirm",
        "place_order": "Place Order",
        "delivery_address_title": "Address",
        "edit_action": "Edit",
        "add_address": "Add Address",
        "digital_delivery_no_address": "Digital delivery",
        "order_summary": "Order Summary",
        "items_total": "Items Total",
        "shipping_total": "Shipping Total",
        "tax_total": "Tax Total",
        "total": "Total",
        "payment_method": "Payment Method",
        "pay_with_card": "Pay with Card",
        "apple_pay": "Apple Pay",
        "google_pay": "Google Pay",
        "confirm_and_pay": "Confirm & Pay",
        "processing": "Processing...",
        "estimated_delivery": "Est. Delivery",
        "local": "Local",
        "local_only_50km": "Local delivery only within 50km",
        "available_local_50km": "Available within 50km of seller",
        "free": "FREE",
        "delivery_options": "Delivery Options",
        "additional_cost": "+\$${"{"}amount}",
        "no_additional_cost": "No additional cost",
        "delivery_speed": {
          "standard": {"name": "Free Delivery", "time": "3-5 business days"},
          "express": {"name": "Express", "time": "1-2 business days"},
          "same_day": {"name": "Same Day", "time": "Delivered today"},
          "international": {"name": "International Standard", "time": "15-30 business days"},
          "international_express": {"name": "International Express", "time": "7-15 business days"},
        },
        "errors": {
          "payment_failed": "Payment failed",
          "invalid_address": "Invalid address",
          "stock_issue": "Stock issue",
          "shipping_calc_failed": "Shipping failed",
          "shipping_unavailable": "Shipping unavailable",
          "no_items": "No items",
          "no_address": "No address",
          "cart_empty": "Cart empty",
          "address_required": "Address required",
          "invalid_total": "Invalid total",
          "missing_email": "Missing email",
          "email_not_verified": "Email not verified",
          "email_verify_failed": "Email verify failed",
          "already_processing": "Already processing",
          "biometric_error": "Biometric error",
          "biometric_failed": "Biometric failed",
          "cart_changed": "Cart changed",
          "items_removed": "Items removed",
          "price_changed": "Price changed",
          "stock_changed": "Stock changed",
        },
      },
      "supplier": {
        "aliexpress": {"display_name": "AliExpress", "region": "Asia", "country": "China", "description": "Global retail marketplace"},
        "alibaba": {"display_name": "Alibaba", "region": "Asia", "country": "China", "description": "B2B wholesale marketplace"},
        "1688": {"display_name": "1688", "region": "Asia", "country": "China", "description": "Chinese domestic B2B platform"},
        "dhgate": {"display_name": "DHgate", "region": "Asia", "country": "China", "description": "Cross-border e-commerce platform"},
        "temu": {"display_name": "Temu", "region": "Asia", "country": "China", "description": "Fast shipping marketplace"},
        "made_in_china": {"display_name": "Made-in-China", "region": "Asia", "country": "China", "description": "B2B sourcing platform"},
        "global_sources": {"display_name": "Global Sources", "region": "Asia", "country": "China/Hong Kong", "description": "Asia-based B2B platform"},
        "cjdropshipping": {
          "display_name": "CJ Dropshipping",
          "region": "Global",
          "country": "China (warehouses worldwide)",
          "description": "Dropshipping & fulfillment service",
        },
        "spocket": {"display_name": "Spocket", "region": "US/EU", "country": "USA/Europe", "description": "US/EU dropshipping suppliers"},
        "printful": {"display_name": "Printful", "region": "Global", "country": "USA/EU/Mexico", "description": "Print-on-demand fulfillment"},
        "printify": {"display_name": "Printify", "region": "Global", "country": "Various", "description": "Print-on-demand platform"},
        "gmarket": {"display_name": "Gmarket", "region": "Asia", "country": "South Korea", "description": "Korean e-commerce platform"},
        "coupang": {"display_name": "Coupang", "region": "Asia", "country": "South Korea", "description": "Korean rocket delivery"},
        "rakuten": {"display_name": "Rakuten", "region": "Asia", "country": "Japan", "description": "Japanese e-commerce giant"},
        "amazon_japan": {"display_name": "Amazon Japan", "region": "Asia", "country": "Japan", "description": "Amazon Japan marketplace"},
        "indiamart": {"display_name": "IndiaMart", "region": "Asia", "country": "India", "description": "Indian B2B marketplace"},
        "tradeindia": {"display_name": "TradeIndia", "region": "Asia", "country": "India", "description": "Indian B2B platform"},
        "faire": {"display_name": "Faire", "region": "US/EU", "country": "USA/Europe", "description": "Wholesale marketplace"},
        "amazon_europe": {"display_name": "Amazon Europe", "region": "Europe", "country": "Germany/UK/France", "description": "Amazon European marketplaces"},
        "amazon_usa": {"display_name": "Amazon USA", "region": "North America", "country": "USA", "description": "Amazon US marketplace"},
        "walmart": {"display_name": "Walmart", "region": "North America", "country": "USA", "description": "US retail giant"},
        "costco": {"display_name": "Costco Business", "region": "North America", "country": "USA/Canada", "description": "Wholesale club"},
        "local": {"display_name": "Local Canadian Supplier", "region": "Canada", "country": "Canada", "description": "Canadian-based supplier"},
        "etsy_wholesale": {"display_name": "Etsy Wholesale", "region": "Global", "country": "Various", "description": "Handmade & vintage items"},
        "custom": {"display_name": "Custom Supplier", "region": "Custom", "country": "Specify", "description": "Add your own supplier details"},
        "other": {"display_name": "Other", "region": "Various", "country": "Various", "description": "Other supplier not listed"},
      },
      "profile": {
        "settings": "Settings",
        "error_loading": "Error loading",
        "setting_up": "Setting up...",
        "sign_in_prompt": "Sign in to see profile",
        "section_navigation": "Navigation",
        "my_orders": "My Orders",
        "view_purchases": "View your purchases",
        "seller_orders": "Seller Orders",
        "manage_sales": "Manage your sales",
        "seller_dashboard": "Seller Dashboard",
        "manage_products_account": "Manage products",
        "start_selling": "Start selling today",
        "admin_panel": "Admin Panel",
        "platform_management": "Platform management",
        "section_settings": "Settings",
        "notifications": "Notifications",
        "manage_notifications": "Manage notifications",
        "address": "Address",
        "manage_delivery_address": "Manage address",
        "terms_conditions": "Terms & Conditions",
        "legal_agreements": "Legal agreements",
        "privacy_policy": "Privacy Policy",
        "how_we_protect": "How we protect you",
        "language": "Language",
        "export_data": "Export Data",
        "export_desc": "Download your data",
        "section_support": "Support",
        "app_info": "App Info",
        "rate_app": "Rate App",
        "rate_app_desc": "Rate us on store",
        "share_app": "Share App",
        "share_app_desc": "Share with friends",
        "share_text": "Check out OrignaGTA!",
        "app_version": "Version {version}",
        "theme": "Theme",
        "theme_desc": "Change app appearance",
        "theme_light": "Light",
        "theme_system": "System",
        "theme_dark": "Dark",
        "delete_account": "Delete Account",
        "delete_warning_short": "This action is irreversible.",
        "type_delete": "Type DELETE to confirm",
        "type_delete_hint": "DELETE",
        "type_delete_keyword": "DELETE",
        "become_seller": "Become a Seller",
        "verify_email_title": "Verify Your Email",
        "verify_email_desc": "Please verify your email to continue.",
        "verify_step_1": "Check your inbox",
        "verify_step_2": "Click the link",
        "verify_step_3": "Come back here",
        "checking_button": "Checking...",
        "verified_button": "I've Verified My Email",
        "sending_button": "Sending...",
        "resend_verification_button": "Resend Verification Email",
        "sign_in_different": "Sign in with a different account",
        "email_verified_snackbar": "Email verified!",
        "not_verified_error": "Email not yet verified",
        "verification_sent": "Verification email sent",
        "export_started": "Export started",
        "completion": "Profile Completion",
        "your_saved_products": "Your saved products",
        "addresses": "Addresses",
        "language_updated": "Language updated",
      },
      "chat": {
        "inbox_title": "Messages",
        "inbox_subtitle": "Your conversations",
        "no_conversations": "No messages",
        "no_conversations_desc": "Start a conversation",
        "type_message": "Type a message",
        "send": "Send",
        "error_loading": "Error loading",
      },
      "favorites": {
        "my_favorites": "Favorites",
        "loading_favorites": "Loading favorites...",
        "empty_favorites": "No favorites",
        "empty_favorites_desc": "You have no favorites yet",
      },
      "subscription": {
        "premium_label": "Premium",
        "status_active": "Active",
        "menu_manage_desc": "Manage subscription",
        "menu_upgrade_desc": "Upgrade to premium",
        "ask_questions": "Ask questions",
        "title": "Subscription",
        "premium_required": "Premium Required",
        "premium_feature_description": "Upgrade to access this feature",
        "upgrade_to_premium": "Upgrade now",
        "plans": "Plans",
        "monthly": "Monthly",
        "price_cad": r"$9.99/mo",
        "subscribe_now": "Subscribe Now",
        "active_plan": "Active Plan",
        "cancel_anytime": "Cancel anytime",
        "success_title": "Welcome to Premium!",
        "success_desc": "You now have full access",
        "cancel_title": "Subscription Cancelled",
        "cancel_desc": "Your access will end at the end of period",
        "premium_membership": "Premium Membership",
        "badge_unlock_premium": "Unlock Premium",
        "price_monthly": r"$9.99 / Month",
        "no_platform_fee": "No Platform Fee",
        "no_platform_fee_desc": "Keep 100% of your sales",
        "chat_with_sellers": "Chat with Sellers",
        "chat_with_sellers_desc": "Instant communication",
        "ask_questions_desc": "Ask about products",
        "smart_notifications": "Smart Notifications",
        "smart_notifications_desc": "Never miss a deal",
        "photo_reviews": "Photo Reviews",
        "photo_reviews_desc": "Share your experience",
        "subscribe_button": "Subscribe",
        "activating_membership": "Activating...",
        "checkout_cancelled": "Cancelled",
        "no_charge_message": "No charge was made",
        "back_to_home": "Back to Home",
      },
      "categories": {
        "electronics": "Electronics",
        "computers": "Computers",
        "gaming": "Gaming",
        "home_kitchen": "Home & Kitchen",
        "fashion": "Fashion",
        "shoes_accessories": "Shoes & Accessories",
        "jewelry_watches": "Jewelry & Watches",
        "beauty_personal_care": "Beauty",
        "health_wellness": "Health",
        "sports_fitness": "Sports",
        "automotive": "Automotive",
        "tools_hardware": "Tools",
        "office_supplies": "Office",
        "books": "Books",
        "music_instruments": "Music",
        "toys_games": "Toys",
        "baby_kids": "Baby",
        "pet_supplies": "Pets",
        "groceries": "Groceries",
        "art_collectibles": "Art",
        "digital_products": "Digital",
      },
      "mascot": {
        "tip_browse": "Browse products",
        "tip_secure": "Secure checkout",
        "tip_ships": "Ships from Canada",
        "tip_rate": "Rate products",
        "tip_find": "Find deals",
        "tip_filter": "Filter by price",
        "tip_questions": "Ask questions",
        "tip_canadian": "Support Canadian sellers",
        "get_help": "Help",
      },
      "rating": {
        "title": "Rating",
        "prompt": "Rate this product",
        "review_body": "Review",
        "review_body_hint": "Enter your review",
        "cancel_label": "Cancel",
        "submit_label": "Submit",
        "add_photos": "Add Photos",
        "upgrade_photos_tooltip": "Premium required",
        "photos_premium_only": "Photos are premium only",
        "star_label": "{count} stars",
        "poor": "Poor",
        "fair": "Fair",
        "good": "Good",
        "very_good": "Very Good",
        "excellent": "Excellent",
        "tap_to_rate": "Tap to rate",
        "thank_you": "Thank you!",
        "error_submitting": "Error submitting",
        "invalid_range": "Invalid range",
      },
      "nav": {"home": "Home", "search": "Search", "cart": "Cart", "favorites": "Favorites", "profile": "Profile"},
      "language": {"en": "English", "fr": "Français", "select_language": "Select Language"},
      "accessibility": {"close_dialog": "Close dialog", "back_button": "Go back"},
      "errors": {"generic_error": "Error", "service_unavailable": "Unavailable", "something_went_wrong": "Something went wrong", "verification_error": "Verification error"},
      "qa": {
        "title": "Q&A",
        "asked_on": "Asked on {date}",
        "answer_label": "Answer",
        "answered": "Answered",
        "your_answer": "Your answer",
        "answer_hint": "Enter answer",
        "submit_answer": "Submit answer",
        "answer_submitted": "Answer submitted",
        "see_all": "See all ({count})",
        "ask_question": "Ask a question",
        "question_hint": "Enter question",
        "submit_question": "Submit question",
        "question_submitted": "Question submitted",
        "sign_in_to_ask": "Sign in to ask",
        "no_questions": "No questions",
      },
      "seller": {
        "manage_orders": "Manage Orders",
        "login_required": "Login Required",
        "login_to_view": "Sign in to view orders",
        "account_suspended": "Account Suspended",
        "contact_support": "Contact support",
        "something_wrong": "Something went wrong",
        "no_orders_yet": "No orders yet",
        "orders_appear_here": "Your orders will appear here",
        "total_earnings": "Total Earnings",
        "after_platform_fee": "After platform fee",
        "pending": "Pending",
        "completed": "Completed",
        "order_prefix": "Order #",
        "your_items": "Your Items",
        "payment_authorized": "Payment Authorized",
        "enter_shipping_cost": "Enter shipping cost",
        "waiting_buyer_approval": "Waiting for buyer",
        "ready_to_capture": "Ready to capture",
        "confirm_shipping_ship": "Confirm Shipping & Ship",
        "delivery_instructions": "Delivery Instructions",
        "qty_prefix": "Qty:",
        "carrier_prefix": "Carrier:",
        "refunded_prefix": "Refunded:",
        "mark_shipped": "Mark Shipped",
        "edit_tracking": "Edit Tracking",
        "status": {"pending": "Pending", "shipped": "Shipped", "delivered": "Delivered", "refunded": "Refunded"},
        "carrier_label": "Carrier",
        "carrier_note_label": "Carrier Note",
        "tracking_number": "Tracking Number",
        "confirm_shipping": "Confirm Shipping",
        "actual_cost": "Actual Cost",
        "carrier_other": "Other",
        "unanswered_questions_plural": "{count} unanswered questions",
        "no_pending_questions": "No pending questions",
        "my_products": "My Products",
        "shipping_approvals": "Shipping Approvals",
        "approve_shipping": "Approve Shipping",
        "buyer_address": "Buyer Address",
        "estimated_shipping_costs": "Estimated Costs",
        "confirm_and_approve": "Confirm & Approve",
        "failed_verify": "Failed to verify",
        "go_home": "Go Home",
        "continue_setup_title": "Continue Setup",
        "continue_setup_body": "Complete setup to start selling",
        "continue_setup": "Continue Setup",
        "back_to_home": "Back to Home",
        "no_pending_approvals": "No pending approvals",
        "approvals_appear_here": "Approvals appear here",
        "login_required_title": "Login Required",
        "login_required_subtitle": "Sign in to manage your business",
        "add_product": "Add Product",
        "products_count": "{count} products",
        "no_products_yet": "No products yet",
        "add_first_product": "Add your first product to start selling",
        "archive_products_title": "Archive Products",
        "archive_confirmation": "Are you sure you want to archive {count} products?",
        "archive": "Archive",
        "under_review": "Under Review",
        "rejected": "Rejected",
        "selected_count": "{count} selected",
        "select_all": "Select All",
        "activate": "Activate",
        "pause": "Pause",
        "archived": "Archived",
        "draft": "Draft",
        "approved": "Approved",
        "active": "Active",
        "rejection_reason_label": "Rejection Reason",
        "fix_and_resubmit": "Fix & Resubmit",
        "stock_count": "{count} in stock",
      },
      "seller_integration": {"title": "Integration"},
      "orders": {
        "my_orders": "My Orders",
        "no_orders": "No orders yet",
        "no_orders_desc": "Your orders will appear here",
        "status": {
          "confirmed": "Confirmed",
          "confirmed_desc": "Order confirmed",
          "processing": "Processing",
          "processing_desc": "Order processing",
          "shipped": "Shipped",
          "shipped_desc": "Order shipped",
          "delivered": "Delivered",
          "refunded": "Refunded",
          "refunded_desc": "Order refunded",
          "cancelled": "Cancelled",
          "cancelled_desc": "Order cancelled",
          "disputed": "Disputed",
          "disputed_desc": "Order disputed",
          "in_transit": "In Transit",
          "in_transit_desc": "In transit",
          "failed": "Failed",
          "failed_desc": "Order failed",
          "expired": "Expired",
          "expired_desc": "Order expired",
          "partially_refunded": "Partially Refunded",
          "partially_refunded_desc": "Partially refunded",
        },
        "license_key": "License Key",
        "license_key_copied": "Copied",
        "orders_need_approval": "{count} need approval",
        "review_shipping_cost": "Review cost",
        "buy_again": "Buy Again",
        "shipping_to": "Shipping to",
        "delivery_instructions": "Delivery Instructions",
        "est_delivery": "Est. delivery: {date}",
        "order_id_prefix": "Order ID: {id}",
        "qty_prefix": "Qty: {count}",
        "confirming": "Confirming...",
        "confirm_receipt": "Confirm Receipt",
        "confirmed_action": "Confirmed",
        "rate_action": "Rate",
        "rated_action": "Rated",
        "payment_waiting_approval": "Waiting approval",
        "payment_authorized": "Authorized",
        "subtotal": "Subtotal",
        "discount": "Discount",
        "shipping": "Shipping",
        "tax": "Tax",
        "total": "Total",
        "unknown_seller": "Unknown Seller",
        "ships_from_canada": "Ships from Canada",
        "ships_international": "Ships International",
        "package_label": "Package {index} of {total}",
        "perishable_chip": "Perishable",
        "perishable_urgency": "Ship soon!",
        "track_package": "Track",
        "receipt_confirmed": "Confirmed",
        "failed_confirm_receipt": "Failed",
        "items_added_to_cart": "{count} added",
        "download_book": "Download Book",
        "download_failed": "Download failed",
        "order_placed": "Order Placed!",
        "order_id_label": "Order ID",
        "thank_you": "Thank you!",
        "continue_shopping": "Continue Shopping",
        "view_my_orders": "View My Orders",
        "order_details": "Order Details",
        "seller_package": "Seller Package",
        "items_count": "{count} items",
        "buy_again_action": "Buy Again",
        "not_found": "Order not found",
      },
      "notifications": {"title": "Notifications", "no_notifications": "No notifications", "no_notifications_desc": "You have no notifications yet"},
      "address": {
        "management_title": "Address Management",
        "add_new": "Add New Address",
        "no_addresses": "No addresses",
        "no_addresses_desc": "Add an address to start",
        "edit_title": "Edit Address",
        "add_title": "Add Address",
        "street": "Street",
        "city": "City",
        "province": "Province",
        "postal_code": "Postal Code",
        "is_default": "Set as default",
        "save": "Save Address",
        "delete": "Delete",
        "delete_confirm": "Are you sure?",
        "count_subtitle": "{count} of {max} addresses saved",
        "add_address": "Add Address",
        "loading": "Loading...",
        "no_address": "No address",
        "add_to_speed_up": "Add to speed up checkout",
        "edit_address": "Edit Address",
        "label": "Label",
        "home": "Home",
        "work": "Work",
        "other": "Other",
        "details": "Details",
        "apartment_optional": "Apartment (optional)",
        "phone": "Phone",
        "save_address": "Save Address",
        "addresses": "Addresses",
        "set_as_default": "Set as Default",
      },
      "terms": {"title": "Terms & Conditions", "last_updated": "Last updated: {date}"},
      "legal": {
        "loading_terms": "Loading...",
        "legal_agreement": "Legal Agreement",
        "terms_conditions_title": "Terms & Conditions",
        "last_updated_february_2026": "Last updated Feb 2026",
        "jump_to_section": "Jump to section",
        "privacy_policy_content": "1. Introduction\nContent here.",
        "privacy_policy_hero": "Privacy Policy",
        "your_privacy_matters": "Your privacy matters",
        "back": "Back",
      },
      "admin": {
        "title": "Admin Panel",
        "sellers_tab": "Sellers",
        "users_tab": "Users",
        "orders_tab": "Orders",
        "products_tab": "Products",
        "payments_tab": "Payments",
        "security_tab": "Security",
        "reviews_tab": "Reviews",
        "loading_panel": "Loading admin panel...",
        "access_denied": "Access Denied",
        "privileges_required": "Admin privileges required",
        "go_home": "Go Home",
        "quick_stats": "Quick Stats",
        "payments": {
          "title": "Payments",
          "description": "Manage payment providers",
          "warning_at_least_one": "At least one provider must be enabled",
          "stripe_name": "Stripe",
          "stripe_desc": "Accept credit cards",
          "enabled_providers": "Enabled Providers",
          "stripe_feature_1": "Feature 1",
          "stripe_feature_2": "Feature 2",
          "stripe_feature_3": "Feature 3",
          "stripe_feature_4": "Feature 4",
          "not_configured": "Not Configured",
          "accepting": "Accepting",
          "not_accepting": "Not Accepting",
        },
        "sellers": {
          "search_hint": "Search products...",
          "filter_all_products": "All Products",
          "filter_in_stock": "In Stock",
          "filter_out_of_stock": "Out of Stock",
          "filter_low_stock": "Low Stock",
          "no_products": "No products found",
          "no_match": "No matching products",
          "low_stock_count": "Low stock ({count})",
          "in_stock_count": "In stock ({count})",
          "set_stock": "Set Stock",
          "mark_out_of_stock": "Mark Out of Stock",
          "view_seller": "View Seller",
          "delete_product": "Delete Product",
          "delete_confirm": "Are you sure you want to delete {name}?",
          "deleted_success": "Product deleted successfully",
          "failed_delete": "Failed to delete product",
          "stock_updated": "Stock updated to {quantity}",
          "failed_stock_update": "Failed to update stock",
          "set_stock_title": "Set Stock Quantity",
          "stock_quantity_label": "Stock Quantity",
          "seller_not_found": "Seller not found",
          "seller_info": "Seller Info",
          "stripe_connected": "Connected",
          "stripe_pending": "Pending",
        },
        "products": {
          "approve_confirm_title": "Approve Product",
          "approve_confirm_body": "Are you sure you want to approve {name}?",
          "approve_action": "Approve",
          "approve_success": "Product approved successfully",
          "approve_error": "Failed to approve product",
          "reject_title": "Reject Product",
          "reject_product_label": "Reject {name}",
          "reject_reason_label": "Reason for rejection",
          "reject_reason_hint": "Enter reason...",
          "reject_action": "Reject",
          "reject_success": "Product rejected successfully",
          "reject_error": "Failed to reject product",
          "download_urls_title": "Download URLs",
          "digital_type_label": "Type: {type}",
          "no_download_urls": "No download URLs available",
        },
        "users": {
          "error_fetching": "Error fetching data",
        },
      },
    };
  }
}
