// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/admin_products_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_riverpod/flutter_riverpod.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:origna_gta/features/admin/admin_actions_viewmodel.dart' as _i2;
import 'package:origna_gta/utils/utils.dart' as _i5;
import 'package:state_notifier/state_notifier.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAdminActionsState_0 extends _i1.SmartFake
    implements _i2.AdminActionsState {
  _FakeAdminActionsState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminActionsViewModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminActionsViewModel extends _i1.Mock
    implements _i2.AdminActionsViewModel {
  @override
  bool get mounted =>
      (super.noSuchMethod(
            Invocation.getter(#mounted),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.Stream<_i2.AdminActionsState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i3.Stream<_i2.AdminActionsState>.empty(),
            returnValueForMissingStub:
                _i3.Stream<_i2.AdminActionsState>.empty(),
          )
          as _i3.Stream<_i2.AdminActionsState>);

  @override
  _i2.AdminActionsState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAdminActionsState_0(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeAdminActionsState_0(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i2.AdminActionsState);

  @override
  _i2.AdminActionsState get debugState =>
      (super.noSuchMethod(
            Invocation.getter(#debugState),
            returnValue: _FakeAdminActionsState_0(
              this,
              Invocation.getter(#debugState),
            ),
            returnValueForMissingStub: _FakeAdminActionsState_0(
              this,
              Invocation.getter(#debugState),
            ),
          )
          as _i2.AdminActionsState);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  set onError(_i4.ErrorListener? value) => super.noSuchMethod(
    Invocation.setter(#onError, value),
    returnValueForMissingStub: null,
  );

  @override
  set state(_i2.AdminActionsState? value) => super.noSuchMethod(
    Invocation.setter(#state, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> approveProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#approveProduct, [productId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> rejectProduct(String? productId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#rejectProduct, [productId, reason]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> disableAdminMfa(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#disableAdminMfa, [code]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<Map<String, dynamic>?> enableAdminMfa() =>
      (super.noSuchMethod(
            Invocation.method(#enableAdminMfa, []),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
            returnValueForMissingStub:
                _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);

  @override
  _i3.Future<_i5.UserModel?> fetchUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUserById, [userId]),
            returnValue: _i3.Future<_i5.UserModel?>.value(),
            returnValueForMissingStub: _i3.Future<_i5.UserModel?>.value(),
          )
          as _i3.Future<_i5.UserModel?>);

  @override
  _i3.Future<bool> setUserSuspended(String? userId, bool? suspended) =>
      (super.noSuchMethod(
            Invocation.method(#setUserSuspended, [userId, suspended]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateProductStock(String? productId, int? quantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateProductStock, [productId, quantity]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateUserRoles(
    String? userId, {
    List<String>? add = const [],
    List<String>? remove = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserRoles,
              [userId],
              {#add: add, #remove: remove},
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> verifyAdminMfa(String? code) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAdminMfa, [code]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  bool updateShouldNotify(
    _i2.AdminActionsState? old,
    _i2.AdminActionsState? current,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShouldNotify, [old, current]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.RemoveListener addListener(
    _i6.Listener<_i2.AdminActionsState>? listener, {
    bool? fireImmediately = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addListener,
              [listener],
              {#fireImmediately: fireImmediately},
            ),
            returnValue: () {},
            returnValueForMissingStub: () {},
          )
          as _i4.RemoveListener);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
