// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/cart_item_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:origna_gta/features/cart/cart_provider.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartController extends _i1.Mock implements _i2.CartController {
  @override
  _i3.Future<bool> addToCart(
    String? productId,
    int? quantity, {
    String? variantId,
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCart,
              [productId, quantity],
              {
                #variantId: variantId,
                #productName: productName,
                #priceCad: priceCad,
              },
            ),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> canAddToCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#canAddToCart, [productId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void refreshCart() => super.noSuchMethod(
    Invocation.method(#refreshCart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> removeFromCart(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [cartItemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> saveForLater(String? productId, String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#saveForLater, [productId, cartItemId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> updateBuyerNote(String? cartItemId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerNote, [cartItemId, note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> updateQuantity(String? cartItemId, int? newQuantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [cartItemId, newQuantity]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);
}
