// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/widget/product_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:typed_data' as _i10;

import 'package:cloud_firestore/cloud_firestore.dart' as _i11;
import 'package:cross_file/cross_file.dart' as _i13;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_auth_platform_interface/firebase_auth_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:origna_gta/core/repositories/product_repository.dart' as _i4;
import 'package:origna_gta/core/schema/schema_constants.dart' as _i12;
import 'package:origna_gta/features/cart/cart_provider.dart' as _i5;
import 'package:origna_gta/features/products/products_provider.dart' as _i7;
import 'package:origna_gta/models/generated/models.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserMetadata_0 extends _i1.SmartFake implements _i2.UserMetadata {
  _FakeUserMetadata_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMultiFactor_1 extends _i1.SmartFake implements _i3.MultiFactor {
  _FakeMultiFactor_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdTokenResult_2 extends _i1.SmartFake implements _i2.IdTokenResult {
  _FakeIdTokenResult_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_3 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeConfirmationResult_4 extends _i1.SmartFake
    implements _i3.ConfirmationResult {
  _FakeConfirmationResult_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUser_5 extends _i1.SmartFake implements _i3.User {
  _FakeUser_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductQueryResult_6 extends _i1.SmartFake
    implements _i4.ProductQueryResult {
  _FakeProductQueryResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CartController].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartController extends _i1.Mock implements _i5.CartController {
  @override
  _i6.Future<bool> addToCart(
    String? productId,
    int? quantity, {
    String? variantId,
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCart,
              [productId, quantity],
              {
                #variantId: variantId,
                #productName: productName,
                #priceCad: priceCad,
              },
            ),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<bool> canAddToCart(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#canAddToCart, [productId]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> clearCart() =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void refreshCart() => super.noSuchMethod(
    Invocation.method(#refreshCart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> removeFromCart(String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [cartItemId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> saveForLater(String? productId, String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#saveForLater, [productId, cartItemId]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> updateBuyerNote(String? cartItemId, String? note) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerNote, [cartItemId, note]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> updateQuantity(String? cartItemId, int? newQuantity) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [cartItemId, newQuantity]),
            returnValue: _i6.Future<bool>.value(false),
            returnValueForMissingStub: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);
}

/// A class which mocks [FavoritesController].
///
/// See the documentation for Mockito's code generation for more information.
class MockFavoritesController extends _i1.Mock
    implements _i7.FavoritesController {
  @override
  bool isFavorite(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#isFavorite, [productId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Future<void> toggleFavorite(
    String? productId, {
    String? productName,
    double? priceCad,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #toggleFavorite,
              [productId],
              {#productName: productName, #priceCad: priceCad},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  bool get emailVerified =>
      (super.noSuchMethod(
            Invocation.getter(#emailVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAnonymous =>
      (super.noSuchMethod(
            Invocation.getter(#isAnonymous),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i2.UserMetadata get metadata =>
      (super.noSuchMethod(
            Invocation.getter(#metadata),
            returnValue: _FakeUserMetadata_0(
              this,
              Invocation.getter(#metadata),
            ),
            returnValueForMissingStub: _FakeUserMetadata_0(
              this,
              Invocation.getter(#metadata),
            ),
          )
          as _i2.UserMetadata);

  @override
  List<_i2.UserInfo> get providerData =>
      (super.noSuchMethod(
            Invocation.getter(#providerData),
            returnValue: <_i2.UserInfo>[],
            returnValueForMissingStub: <_i2.UserInfo>[],
          )
          as List<_i2.UserInfo>);

  @override
  String get uid =>
      (super.noSuchMethod(
            Invocation.getter(#uid),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#uid)),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.getter(#uid),
            ),
          )
          as String);

  @override
  _i3.MultiFactor get multiFactor =>
      (super.noSuchMethod(
            Invocation.getter(#multiFactor),
            returnValue: _FakeMultiFactor_1(
              this,
              Invocation.getter(#multiFactor),
            ),
            returnValueForMissingStub: _FakeMultiFactor_1(
              this,
              Invocation.getter(#multiFactor),
            ),
          )
          as _i3.MultiFactor);

  @override
  _i6.Future<void> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdToken, [forceRefresh]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<_i2.IdTokenResult> getIdTokenResult([
    bool? forceRefresh = false,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#getIdTokenResult, [forceRefresh]),
            returnValue: _i6.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i2.IdTokenResult>.value(
              _FakeIdTokenResult_2(
                this,
                Invocation.method(#getIdTokenResult, [forceRefresh]),
              ),
            ),
          )
          as _i6.Future<_i2.IdTokenResult>);

  @override
  _i6.Future<_i3.UserCredential> linkWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithCredential, [credential]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithCredential, [credential]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<_i3.UserCredential> linkWithProvider(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithProvider, [provider]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithProvider, [provider]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<_i3.UserCredential> reauthenticateWithProvider(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithProvider, [provider]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithProvider, [provider]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<_i3.UserCredential> reauthenticateWithPopup(
    _i2.AuthProvider? provider,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithPopup, [provider]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithPopup, [provider]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<void> reauthenticateWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithRedirect, [provider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.UserCredential> linkWithPopup(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPopup, [provider]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#linkWithPopup, [provider]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<void> linkWithRedirect(_i2.AuthProvider? provider) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithRedirect, [provider]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#linkWithPhoneNumber, [phoneNumber, verifier]),
            returnValue: _i6.Future<_i3.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.ConfirmationResult>.value(
              _FakeConfirmationResult_4(
                this,
                Invocation.method(#linkWithPhoneNumber, [
                  phoneNumber,
                  verifier,
                ]),
              ),
            ),
          )
          as _i6.Future<_i3.ConfirmationResult>);

  @override
  _i6.Future<_i3.UserCredential> reauthenticateWithCredential(
    _i2.AuthCredential? credential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reauthenticateWithCredential, [credential]),
            returnValue: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i3.UserCredential>.value(
              _FakeUserCredential_3(
                this,
                Invocation.method(#reauthenticateWithCredential, [credential]),
              ),
            ),
          )
          as _i6.Future<_i3.UserCredential>);

  @override
  _i6.Future<void> reload() =>
      (super.noSuchMethod(
            Invocation.method(#reload, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> sendEmailVerification([
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, [actionCodeSettings]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i3.User> unlink(String? providerId) =>
      (super.noSuchMethod(
            Invocation.method(#unlink, [providerId]),
            returnValue: _i6.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
            returnValueForMissingStub: _i6.Future<_i3.User>.value(
              _FakeUser_5(this, Invocation.method(#unlink, [providerId])),
            ),
          )
          as _i6.Future<_i3.User>);

  @override
  _i6.Future<void> updatePassword(String? newPassword) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [newPassword]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhoneNumber(
    _i2.PhoneAuthCredential? phoneCredential,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhoneNumber, [phoneCredential]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
            Invocation.method(#updateDisplayName, [displayName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updatePhotoURL(String? photoURL) =>
      (super.noSuchMethod(
            Invocation.method(#updatePhotoURL, [photoURL]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProfile({String? displayName, String? photoURL}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #photoURL: photoURL,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i2.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBeforeUpdateEmail, [
              newEmail,
              actionCodeSettings,
            ]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [ProductRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductRepository extends _i1.Mock implements _i4.ProductRepository {
  @override
  _i6.Future<String> createProductAtomic(
    _i9.Product? product,
    List<_i10.Uint8List>? imageBytes, {
    List<String>? testImageUrls,
    String? bookSourceUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createProductAtomic,
              [product, imageBytes],
              {#testImageUrls: testImageUrls, #bookSourceUrl: bookSourceUrl},
            ),
            returnValue: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i6.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #createProductAtomic,
                  [product, imageBytes],
                  {
                    #testImageUrls: testImageUrls,
                    #bookSourceUrl: bookSourceUrl,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<String>);

  @override
  _i6.Future<void> deleteProduct(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [productId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<_i9.Product?> fetchProductById(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductById, [productId]),
            returnValue: _i6.Future<_i9.Product?>.value(),
            returnValueForMissingStub: _i6.Future<_i9.Product?>.value(),
          )
          as _i6.Future<_i9.Product?>);

  @override
  _i6.Future<_i4.ProductQueryResult> fetchProducts({
    String? searchQuery,
    int? categoryId,
    String? subcategory,
    _i11.DocumentSnapshot<Object?>? lastDocument,
    int? pageSize = 20,
    _i12.SortOption? sortOption = _i12.SortOption.relevance,
    int? minPriceCents,
    int? maxPriceCents,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProducts, [], {
              #searchQuery: searchQuery,
              #categoryId: categoryId,
              #subcategory: subcategory,
              #lastDocument: lastDocument,
              #pageSize: pageSize,
              #sortOption: sortOption,
              #minPriceCents: minPriceCents,
              #maxPriceCents: maxPriceCents,
            }),
            returnValue: _i6.Future<_i4.ProductQueryResult>.value(
              _FakeProductQueryResult_6(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocument: lastDocument,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
            returnValueForMissingStub: _i6.Future<_i4.ProductQueryResult>.value(
              _FakeProductQueryResult_6(
                this,
                Invocation.method(#fetchProducts, [], {
                  #searchQuery: searchQuery,
                  #categoryId: categoryId,
                  #subcategory: subcategory,
                  #lastDocument: lastDocument,
                  #pageSize: pageSize,
                  #sortOption: sortOption,
                  #minPriceCents: minPriceCents,
                  #maxPriceCents: maxPriceCents,
                }),
              ),
            ),
          )
          as _i6.Future<_i4.ProductQueryResult>);

  @override
  _i6.Future<List<_i9.Product>> fetchProductsByIds(List<String>? productIds) =>
      (super.noSuchMethod(
            Invocation.method(#fetchProductsByIds, [productIds]),
            returnValue: _i6.Future<List<_i9.Product>>.value(<_i9.Product>[]),
            returnValueForMissingStub: _i6.Future<List<_i9.Product>>.value(
              <_i9.Product>[],
            ),
          )
          as _i6.Future<List<_i9.Product>>);

  @override
  String generateProductId() =>
      (super.noSuchMethod(
            Invocation.method(#generateProductId, []),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
            returnValueForMissingStub: _i8.dummyValue<String>(
              this,
              Invocation.method(#generateProductId, []),
            ),
          )
          as String);

  @override
  _i6.Future<List<Map<String, dynamic>>> getAutocompleteSuggestions(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAutocompleteSuggestions, [query]),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
            returnValueForMissingStub:
                _i6.Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[],
                ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<_i9.Product?> getProductBySlug(String? slug) =>
      (super.noSuchMethod(
            Invocation.method(#getProductBySlug, [slug]),
            returnValue: _i6.Future<_i9.Product?>.value(),
            returnValueForMissingStub: _i6.Future<_i9.Product?>.value(),
          )
          as _i6.Future<_i9.Product?>);

  @override
  _i6.Future<String?> getUploadUrl(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrl, [fileName]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<Map<String, String>?> getUploadUrlInfo(String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadUrlInfo, [fileName]),
            returnValue: _i6.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i6.Future<Map<String, String>?>.value(),
          )
          as _i6.Future<Map<String, String>?>);

  @override
  _i6.Future<Map<String, String>?> getUploadVideoUrlInfo(
    String? fileName,
    String? contentType,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUploadVideoUrlInfo, [fileName, contentType]),
            returnValue: _i6.Future<Map<String, String>?>.value(),
            returnValueForMissingStub: _i6.Future<Map<String, String>?>.value(),
          )
          as _i6.Future<Map<String, String>?>);

  @override
  _i6.Future<void> submitRating(
    String? orderId,
    String? productId,
    int? rating, {
    List<String>? reviewImageUrls,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRating,
              [orderId, productId, rating],
              {#reviewImageUrls: reviewImageUrls, #reviewText: reviewText},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> submitRatingAtomic(
    String? orderId,
    String? productId,
    int? rating, {
    List<_i10.Uint8List>? reviewImages,
    String? reviewText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitRatingAtomic,
              [orderId, productId, rating],
              {#reviewImages: reviewImages, #reviewText: reviewText},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> toggleFavorite(String? userId, String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleFavorite, [userId, productId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [productId, data]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> uploadImages(
    List<_i10.Uint8List>? images,
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImages, [images, productId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<String?> uploadProductVideo(
    _i13.XFile? videoFile,
    String? sellerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadProductVideo, [videoFile, sellerId]),
            returnValue: _i6.Future<String?>.value(),
            returnValueForMissingStub: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  _i6.Future<List<String>> uploadReviewImages(
    List<_i10.Uint8List>? images,
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadReviewImages, [images, userId]),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i6.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Stream<Set<String>> watchFavorites(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchFavorites, [userId]),
            returnValue: _i6.Stream<Set<String>>.empty(),
            returnValueForMissingStub: _i6.Stream<Set<String>>.empty(),
          )
          as _i6.Stream<Set<String>>);

  @override
  _i6.Stream<int> watchUnansweredQuestionsCount(String? sellerId) =>
      (super.noSuchMethod(
            Invocation.method(#watchUnansweredQuestionsCount, [sellerId]),
            returnValue: _i6.Stream<int>.empty(),
            returnValueForMissingStub: _i6.Stream<int>.empty(),
          )
          as _i6.Stream<int>);
}
