// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/cart_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:origna_gta/core/repositories/cart_repository.dart' as _i2;
import 'package:origna_gta/utils/utils.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CartRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCartRepository extends _i1.Mock implements _i2.CartRepository {
  @override
  _i3.Future<void> addToCart(
    String? userId,
    String? productId,
    int? quantity, {
    String? variantId,
    String? variantTitle,
    Map<String, String>? variantOptions,
    String? variantSku,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addToCart,
              [userId, productId, quantity],
              {
                #variantId: variantId,
                #variantTitle: variantTitle,
                #variantOptions: variantOptions,
                #variantSku: variantSku,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> clearCart(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#clearCart, [userId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<String?> getProductSellerId(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductSellerId, [productId]),
            returnValue: _i3.Future<String?>.value(),
            returnValueForMissingStub: _i3.Future<String?>.value(),
          )
          as _i3.Future<String?>);

  @override
  _i3.Future<bool> isVariantValid(String? productId, String? variantId) =>
      (super.noSuchMethod(
            Invocation.method(#isVariantValid, [productId, variantId]),
            returnValue: _i3.Future<bool>.value(false),
            returnValueForMissingStub: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> removeFromCart(String? userId, String? cartItemId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromCart, [userId, cartItemId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateBuyerNote(
    String? userId,
    String? cartItemId,
    String? note,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerNote, [userId, cartItemId, note]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateQuantity(
    String? userId,
    String? cartItemId,
    int? quantity,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateQuantity, [userId, cartItemId, quantity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.CartItemModel>> watchCart(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchCart, [userId]),
            returnValue: _i3.Stream<List<_i4.CartItemModel>>.empty(),
            returnValueForMissingStub:
                _i3.Stream<List<_i4.CartItemModel>>.empty(),
          )
          as _i3.Stream<List<_i4.CartItemModel>>);
}
