// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/checkout_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:cloud_functions/cloud_functions.dart' as _i6;
import 'package:cloud_functions_platform_interface/cloud_functions_platform_interface.dart'
    as _i4;
import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:firebase_core/firebase_core.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:origna_gta/core/repositories/auth_repository.dart' as _i12;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i7;
import 'package:origna_gta/core/repositories/user_repository.dart' as _i2;
import 'package:origna_gta/models/generated/models.dart' as _i9;
import 'package:origna_gta/utils/utils.dart' as _i10;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSellerAccountStatus_0 extends _i1.SmartFake
    implements _i2.SellerAccountStatus {
  _FakeSellerAccountStatus_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserCredential_1 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFunctionsPlatform_2 extends _i1.SmartFake
    implements _i4.FirebaseFunctionsPlatform {
  _FakeFirebaseFunctionsPlatform_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseApp_3 extends _i1.SmartFake implements _i5.FirebaseApp {
  _FakeFirebaseApp_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallable_4 extends _i1.SmartFake implements _i6.HttpsCallable {
  _FakeHttpsCallable_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallablePlatform_5 extends _i1.SmartFake
    implements _i4.HttpsCallablePlatform {
  _FakeHttpsCallablePlatform_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpsCallableResult_6<T1> extends _i1.SmartFake
    implements _i6.HttpsCallableResult<T1> {
  _FakeHttpsCallableResult_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i7.OrderRepository {
  @override
  _i8.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<_i9.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i8.Future<_i9.Order?>.value(),
            returnValueForMissingStub: _i8.Future<_i9.Order?>.value(),
          )
          as _i8.Future<_i9.Order?>);

  @override
  _i8.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateShippingCost(
    String? orderId,
    double? newShippingCost,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCost,
              reason,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i9.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i8.Stream<List<_i9.Order>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<_i9.Order>>.empty(),
          )
          as _i8.Stream<List<_i9.Order>>);

  @override
  _i8.Stream<_i9.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i8.Stream<_i9.Order?>.empty(),
            returnValueForMissingStub: _i8.Stream<_i9.Order?>.empty(),
          )
          as _i8.Stream<_i9.Order?>);

  @override
  _i8.Stream<List<_i9.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i8.Stream<List<_i9.Order>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<_i9.Order>>.empty(),
          )
          as _i8.Stream<List<_i9.Order>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i8.Future<String> addBuyerAddress(_i10.Address? address) =>
      (super.noSuchMethod(
            Invocation.method(#addBuyerAddress, [address]),
            returnValue: _i8.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#addBuyerAddress, [address]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> deleteBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBuyerAddress, [addressId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i2.SellerAccountStatus> getSellerAccountStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getSellerAccountStatus, [userId]),
            returnValue: _i8.Future<_i2.SellerAccountStatus>.value(
              _FakeSellerAccountStatus_0(
                this,
                Invocation.method(#getSellerAccountStatus, [userId]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i2.SellerAccountStatus>.value(
                  _FakeSellerAccountStatus_0(
                    this,
                    Invocation.method(#getSellerAccountStatus, [userId]),
                  ),
                ),
          )
          as _i8.Future<_i2.SellerAccountStatus>);

  @override
  _i8.Future<_i10.UserModel?> getUserProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i8.Future<_i10.UserModel?>.value(),
            returnValueForMissingStub: _i8.Future<_i10.UserModel?>.value(),
          )
          as _i8.Future<_i10.UserModel?>);

  @override
  _i8.Future<void> recordTermsAcceptance() =>
      (super.noSuchMethod(
            Invocation.method(#recordTermsAcceptance, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setDefaultBuyerAddress(String? addressId) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaultBuyerAddress, [addressId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateBuyerAddress(
    String? addressId,
    _i10.Address? address,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBuyerAddress, [addressId, address]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateNotificationPreferences(
    String? userId, {
    bool? notifyNewProducts,
    bool? notifyTrending,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNotificationPreferences,
              [userId],
              {
                #notifyNewProducts: notifyNewProducts,
                #notifyTrending: notifyTrending,
              },
            ),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updatePreferredLanguage(String? userId, String? lang) =>
      (super.noSuchMethod(
            Invocation.method(#updatePreferredLanguage, [userId, lang]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i10.Address>> watchAddresses(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchAddresses, [userId]),
            returnValue: _i8.Stream<List<_i10.Address>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<_i10.Address>>.empty(),
          )
          as _i8.Stream<List<_i10.Address>>);

  @override
  _i8.Stream<_i2.SellerAccountStatus> watchSellerAccountStatus(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerAccountStatus, [userId]),
            returnValue: _i8.Stream<_i2.SellerAccountStatus>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i2.SellerAccountStatus>.empty(),
          )
          as _i8.Stream<_i2.SellerAccountStatus>);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i12.AuthRepository {
  @override
  _i8.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> ensureUserDocumentExists() =>
      (super.noSuchMethod(
            Invocation.method(#ensureUserDocumentExists, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> isEmailVerified() =>
      (super.noSuchMethod(
            Invocation.method(#isEmailVerified, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i3.UserCredential> registerWithEmail(
    String? email,
    String? password,
    String? name, {
    bool? marketingOptIn = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #registerWithEmail,
              [email, password, name],
              {#marketingOptIn: marketingOptIn},
            ),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(
                  #registerWithEmail,
                  [email, password, name],
                  {#marketingOptIn: marketingOptIn},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(
                  #registerWithEmail,
                  [email, password, name],
                  {#marketingOptIn: marketingOptIn},
                ),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<void> sendEmailVerification() =>
      (super.noSuchMethod(
            Invocation.method(#sendEmailVerification, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#sendPasswordResetEmail, [email]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i3.UserCredential> signInWithApple() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithApple, []),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithApple, []),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<_i3.UserCredential> signInWithEmail(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmail, [email, password]),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithEmail, [email, password]),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<_i3.UserCredential> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i3.UserCredential>.value(
              _FakeUserCredential_1(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i8.Future<_i3.UserCredential>);

  @override
  _i8.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> validateCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#validateCurrentUser, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Stream<_i10.UserModel?> watchProfile(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, [userId]),
            returnValue: _i8.Stream<_i10.UserModel?>.empty(),
            returnValueForMissingStub: _i8.Stream<_i10.UserModel?>.empty(),
          )
          as _i8.Stream<_i10.UserModel?>);
}

/// A class which mocks [FirebaseFunctions].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseFunctions extends _i1.Mock implements _i6.FirebaseFunctions {
  @override
  _i4.FirebaseFunctionsPlatform get delegate =>
      (super.noSuchMethod(
            Invocation.getter(#delegate),
            returnValue: _FakeFirebaseFunctionsPlatform_2(
              this,
              Invocation.getter(#delegate),
            ),
            returnValueForMissingStub: _FakeFirebaseFunctionsPlatform_2(
              this,
              Invocation.getter(#delegate),
            ),
          )
          as _i4.FirebaseFunctionsPlatform);

  @override
  _i5.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_3(this, Invocation.getter(#app)),
            returnValueForMissingStub: _FakeFirebaseApp_3(
              this,
              Invocation.getter(#app),
            ),
          )
          as _i5.FirebaseApp);

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
            returnValueForMissingStub: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i6.HttpsCallable httpsCallable(
    String? name, {
    _i6.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#httpsCallable, [name], {#options: options}),
            returnValue: _FakeHttpsCallable_4(
              this,
              Invocation.method(#httpsCallable, [name], {#options: options}),
            ),
            returnValueForMissingStub: _FakeHttpsCallable_4(
              this,
              Invocation.method(#httpsCallable, [name], {#options: options}),
            ),
          )
          as _i6.HttpsCallable);

  @override
  _i6.HttpsCallable httpsCallableFromUrl(
    String? url, {
    _i6.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #httpsCallableFromUrl,
              [url],
              {#options: options},
            ),
            returnValue: _FakeHttpsCallable_4(
              this,
              Invocation.method(
                #httpsCallableFromUrl,
                [url],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeHttpsCallable_4(
              this,
              Invocation.method(
                #httpsCallableFromUrl,
                [url],
                {#options: options},
              ),
            ),
          )
          as _i6.HttpsCallable);

  @override
  _i6.HttpsCallable httpsCallableFromUri(
    Uri? uri, {
    _i6.HttpsCallableOptions? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #httpsCallableFromUri,
              [uri],
              {#options: options},
            ),
            returnValue: _FakeHttpsCallable_4(
              this,
              Invocation.method(
                #httpsCallableFromUri,
                [uri],
                {#options: options},
              ),
            ),
            returnValueForMissingStub: _FakeHttpsCallable_4(
              this,
              Invocation.method(
                #httpsCallableFromUri,
                [uri],
                {#options: options},
              ),
            ),
          )
          as _i6.HttpsCallable);

  @override
  void useFunctionsEmulator(
    String? host,
    int? port, {
    bool? automaticHostMapping = true,
  }) => super.noSuchMethod(
    Invocation.method(
      #useFunctionsEmulator,
      [host, port],
      {#automaticHostMapping: automaticHostMapping},
    ),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HttpsCallable].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpsCallable extends _i1.Mock implements _i6.HttpsCallable {
  @override
  _i4.HttpsCallablePlatform get delegate =>
      (super.noSuchMethod(
            Invocation.getter(#delegate),
            returnValue: _FakeHttpsCallablePlatform_5(
              this,
              Invocation.getter(#delegate),
            ),
            returnValueForMissingStub: _FakeHttpsCallablePlatform_5(
              this,
              Invocation.getter(#delegate),
            ),
          )
          as _i4.HttpsCallablePlatform);

  @override
  _i8.Future<_i6.HttpsCallableResult<T>> call<T>([dynamic parameters]) =>
      (super.noSuchMethod(
            Invocation.method(#call, [parameters]),
            returnValue: _i8.Future<_i6.HttpsCallableResult<T>>.value(
              _FakeHttpsCallableResult_6<T>(
                this,
                Invocation.method(#call, [parameters]),
              ),
            ),
            returnValueForMissingStub:
                _i8.Future<_i6.HttpsCallableResult<T>>.value(
                  _FakeHttpsCallableResult_6<T>(
                    this,
                    Invocation.method(#call, [parameters]),
                  ),
                ),
          )
          as _i8.Future<_i6.HttpsCallableResult<T>>);

  @override
  _i8.Stream<_i6.StreamResponse<T, R>> stream<T, R>([Object? input]) =>
      (super.noSuchMethod(
            Invocation.method(#stream, [input]),
            returnValue: _i8.Stream<_i6.StreamResponse<T, R>>.empty(),
            returnValueForMissingStub:
                _i8.Stream<_i6.StreamResponse<T, R>>.empty(),
          )
          as _i8.Stream<_i6.StreamResponse<T, R>>);
}

/// A class which mocks [HttpsCallableResult].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpsCallableResult<T> extends _i1.Mock
    implements _i6.HttpsCallableResult<T> {
  @override
  T get data =>
      (super.noSuchMethod(
            Invocation.getter(#data),
            returnValue: _i11.dummyValue<T>(this, Invocation.getter(#data)),
            returnValueForMissingStub: _i11.dummyValue<T>(
              this,
              Invocation.getter(#data),
            ),
          )
          as T);
}
