// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/qa_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:origna_gta/features/qa/qa_repository.dart' as _i2;
import 'package:origna_gta/models/qa_model.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [QARepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockQARepository extends _i1.Mock implements _i2.QARepository {
  @override
  _i3.Future<void> submitAnswer(String? qaId, String? answer) =>
      (super.noSuchMethod(
            Invocation.method(#submitAnswer, [qaId, answer]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> submitQuestion(String? productId, String? question) =>
      (super.noSuchMethod(
            Invocation.method(#submitQuestion, [productId, question]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.QAModel>> watchQA(String? productId) =>
      (super.noSuchMethod(
            Invocation.method(#watchQA, [productId]),
            returnValue: _i3.Stream<List<_i4.QAModel>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.QAModel>>.empty(),
          )
          as _i3.Stream<List<_i4.QAModel>>);
}
