// Mocks generated by Mockito 5.4.6 from annotations
// in origna_gta/test/unit/seller_orders_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:origna_gta/core/repositories/order_repository.dart' as _i2;
import 'package:origna_gta/models/generated/models.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [OrderRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrderRepository extends _i1.Mock implements _i2.OrderRepository {
  @override
  _i3.Future<void> approveShippingCost(String? orderId, bool? approved) =>
      (super.noSuchMethod(
            Invocation.method(#approveShippingCost, [orderId, approved]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> capturePayment(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#capturePayment, [orderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> confirmReceipt(String? orderId, {String? productId}) =>
      (super.noSuchMethod(
            Invocation.method(
              #confirmReceipt,
              [orderId],
              {#productId: productId},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> createCheckoutSession(
    Map<String, dynamic>? orderData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCheckoutSession, [orderData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<_i4.Order?> fetchOrderById(String? orderId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchOrderById, [orderId]),
            returnValue: _i3.Future<_i4.Order?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Order?>.value(),
          )
          as _i3.Future<_i4.Order?>);

  @override
  _i3.Future<void> updateItemStatus(
    String? orderId,
    String? itemId,
    String? status, {
    String? trackingNumber,
    String? carrier,
    String? carrierNote,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateItemStatus,
              [orderId, itemId, status],
              {
                #trackingNumber: trackingNumber,
                #carrier: carrier,
                #carrierNote: carrierNote,
              },
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateLastSession(
    String? userId,
    String? sessionId,
    String? orderId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateLastSession, [userId, sessionId, orderId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateShippingCost(
    String? orderId,
    double? newShippingCost,
    String? reason,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateShippingCost, [
              orderId,
              newShippingCost,
              reason,
            ]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<List<_i4.Order>> watchBuyerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchBuyerOrders, [userId]),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);

  @override
  _i3.Stream<_i4.Order?> watchPaidOrderBySession(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPaidOrderBySession, [sessionId]),
            returnValue: _i3.Stream<_i4.Order?>.empty(),
            returnValueForMissingStub: _i3.Stream<_i4.Order?>.empty(),
          )
          as _i3.Stream<_i4.Order?>);

  @override
  _i3.Stream<List<_i4.Order>> watchSellerOrders(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#watchSellerOrders, [userId]),
            returnValue: _i3.Stream<List<_i4.Order>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.Order>>.empty(),
          )
          as _i3.Stream<List<_i4.Order>>);
}
