import 'dart:math';

import 'package:flutter/foundation.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'flows/smoke_home_profile_test.dart' as smoke;
import 'flows/add_product_flow_test.dart' as add_product;
import 'flows/buyer_flow_test.dart' as buyer;
import 'flows/seller_flow_test.dart' as seller;
import 'flows/admin_flow_test.dart' as admin;
import 'flows/edge_navigation_test.dart' as edge;

/// G00 — All Integration Flows
///
/// Aggregator that runs all 6 flow test suites:
/// - Smoke (Home + Profile)
/// - Add Product (Product creation flows)
/// - Buyer (Browse, cart, checkout)
/// - Seller (Seller tools, seller orders)
/// - Admin (Admin panel, privileged menu)
/// - Edge (Deep links, error states, misc)
///
/// Run individually:
/// ```bash
/// flutter drive --target=integration_test/flows/smoke_home_profile_test.dart
/// flutter drive --target=integration_test/flows/add_product_flow_test.dart
/// flutter drive --target=integration_test/flows/buyer_flow_test.dart
/// flutter drive --target=integration_test/flows/seller_flow_test.dart
/// flutter drive --target=integration_test/flows/admin_flow_test.dart
/// flutter drive --target=integration_test/flows/edge_navigation_test.dart
/// ```
///
/// Run all:
/// ```bash
/// flutter drive --target=integration_test/all_tests.dart
/// ```
///
/// ## Flutter integration tests (web)
///
/// DEV Firebase only (no emulators): credentials must be provided via
/// `--dart-define` or `--dart-define-from-file`.
///
/// Run with credentials from logs (generated by `scripts/generate_integration_dart_defines.py`):
/// ```bash
/// cd origna_gta
/// flutter drive --driver=test_driver/integration_test.dart \
///   --target=integration_test/all_tests.dart \
///   -d chrome \
///   --dart-define=ENVIRONMENT=dev \
///   --dart-define=IS_TEST=true \
///   --dart-define-from-file=../logs/integration_dart_defines.dev.json
/// ```
///
/// To force a specific test (e.g. Buyer Flow = 2):
/// ```bash
/// --dart-define=INTEGRATION_TEST_INDEX=2
/// ```

void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  const env = String.fromEnvironment('ENVIRONMENT', defaultValue: 'production');
  if (env != 'dev') {
    throw StateError(
      'Integration tests are DEV Firebase only. '
      'Re-run with --dart-define=ENVIRONMENT=dev (current ENVIRONMENT=$env).',
    );
  }

  // Select ONE test to run (0-5)
  // - Default: random selection
  // - Override: --dart-define=INTEGRATION_TEST_INDEX=2 (for example)
  const forcedIndex = int.fromEnvironment(
    'INTEGRATION_TEST_INDEX',
    defaultValue: -1,
  );

  final selectedTest = (forcedIndex >= 0 && forcedIndex < 6)
      ? forcedIndex
      : Random().nextInt(6);

  final testNames = [
    'Smoke Test (Home + Profile)',
    'Add Product Flow',
    'Buyer Flow',
    'Seller Flow',
    'Admin Flow',
    'Edge Navigation Flow',
  ];

  debugPrint('');
  debugPrint('═══════════════════════════════════════════════════════');
  debugPrint('🎲 RANDOM TEST SELECTION MODE');
  debugPrint(
    '   Selected: ${testNames[selectedTest]} (index $selectedTest) '
    '${forcedIndex >= 0 ? '(forced)' : ''}',
  );
  debugPrint('═══════════════════════════════════════════════════════');
  debugPrint('');

  group('G00 — All Integration Flows', () {
    if (forcedIndex >= 0 && forcedIndex < 6) {
      switch (forcedIndex) {
        case 0:
          smoke.main();
          break;
        case 1:
          add_product.main();
          break;
        case 2:
          buyer.main();
          break;
        case 3:
          seller.main();
          break;
        case 4:
          admin.main();
          break;
        case 5:
          edge.main();
          break;
      }
    } else {
      // Run ALL
      smoke.main();
      add_product.main();
      buyer.main();
      seller.main();
      admin.main();
      edge.main();
    }
  });
}
